<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => 'Действие',
    'Are you sure you want to delete this item?' => 'Вы уверенны, что хотите удалить эту запись?',
    'Choosing the language of translation' => 'Выберите язык перевода',
    'Create' => 'Создать',
    'Create {modelClass}' => 'Создать {modelClass}',
    'Delete' => 'Удалить',
    'Delete selected' => 'Удалить выбранные',
    'Enter "{command}" to search for empty translations.' => 'Введите "{command}" для поиска пустых переводов',
    'Export' => 'Экспорт',
    'Home' => 'Домой',
    'Im-/Export' => 'Им-/Экспорт',
    'Import' => 'импорт',
    'Invalid model "{model}":' => 'Неправильная модель "{model}":',
    'Language' => 'Язык',
    'Languages' => 'Языки',
    'List of languages' => 'Список языков',
    'Optimise database' => 'Оптимизировать базу данных',
    'Optimize' => 'Оптимизировать',
    'Original' => 'Оригинальный',
    'Save' => 'Сохранить',
    'Scan' => 'Сканировать',
    'Scanning project' => 'Сканировать проэкт',
    'Select all' => 'Выбрать все',
    'Source' => 'Текст',
    'Source language' => 'Исходный язык',
    'Statistic' => 'Статистика',
    'Status' => 'Статус',
    'Successfully imported {fileName}' => 'Успешно импортирован {fileName}',
    'Text not found in database! Please run project scan before translating!' => 'Текст не найден в базе данных! Пожалуйста запустите сканирование!',
    'Text to be translated' => 'Текст для перевода',
    'Toggle translate' => 'Переключить перевод',
    'Translate' => 'Перевести',
    'Translation' => 'Перевод',
    'Translation into {language_id}' => 'Перевод в {language_id}',
    'Translation status' => 'Статус перевода',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить {modelClass}: ',
    'translations' => 'переводы',
    '{n, plural, =0{No entries} =1{One entry} other{# entries}} remove!' => '{n, plural, =0{ни одной записи не было} =1{одну запись} other{# записей}} удалено!',
    '{n, plural, =0{No entries} =1{One entry} other{# entries}} were removed!' => '{n, plural, =0{ни одной записи не было} =1{одну запись} other{# записей}} удалено!',
    '{n, plural, =0{No new entries} =1{One new entry} other{# new entries}} were added!' => '{n, plural, =0{ни одной новой записи не} =1{одну новую запись} other{# новых записей}} было добавлено!',
    '{type}: {new} new, {updated} updated' => '{type}: {new} создано, {updated} обновлено',
];
